services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgressql/data

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    expose:
      - 5432

    restart: always

  
  backend:
    container_name: Practice-Project
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/DockerFile
    
    volumes:
      - ./core:/usr/src/app
    working_dir : /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=False
    
    restart: always
    ports: 
      - 8000:8000
    
    depends_on:
      - db
