# Generated by Django 5.2.4 on 2025-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.IntegerField(choices=[(1, 'No_Subscription'), (2, 'Day'), (3, 'week'), (4, 'month_1'), (5, 'month_3'), (6, 'month_6'), (7, 'month_12')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_exp',
            field=models.DateTimeField(null=True),
        ),
    ]
