# Generated by Django 5.2.4 on 2025-07-18 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_subscription_user_subscription_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsCriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_type', models.IntegerField(choices=[(1, 'No_Subscription'), (2, 'Day'), (3, 'week'), (4, 'month_1'), (5, 'month_3'), (6, 'month_6'), (7, 'month_12')], default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
