# Generated by Django 5.2.4 on 2025-07-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscriptionmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubsCriptionModel',
            new_name='UserSubscriptionModel',
        ),
    ]
