# Generated by Django 5.2.4 on 2025-07-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_subscription_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.IntegerField(choices=[(1, 'No_Subscription'), (2, 'days_10'), (3, 'days_15'), (4, 'days_30'), (5, 'days_60')], default=1),
        ),
        migrations.AlterField(
            model_name='usersubscriptionmodel',
            name='subs_type',
            field=models.IntegerField(choices=[(1, 'No_Subscription'), (2, 'days_10'), (3, 'days_15'), (4, 'days_30'), (5, 'days_60')], default=1),
        ),
    ]
