# Generated by Django 5.2.4 on 2025-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
