# Generated by Django 5.2.4 on 2025-08-04 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_usersubscriptionmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscriptionmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
