# Generated by Django 5.2.4 on 2025-08-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_created_date_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='UserSubscriptionModel',
        ),
    ]
