# Generated by Django 5.2.4 on 2025-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'زمان'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'حساب کاربری'},
        ),
    ]
