# Generated by Django 5.2.4 on 2025-08-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب کاربری'},
        ),
    ]
