# Generated by Django 5.2.4 on 2025-07-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
