# Generated by Django 5.2.4 on 2025-07-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_wishlist_wishlistmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='blogs/'),
        ),
    ]
