# Generated by Django 5.2.4 on 2025-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_peymentmodel_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='authority_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
