# Generated by Django 5.2.4 on 2025-07-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentmodel_authority_id_paymentmodel_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='user',
        ),
    ]
