# Generated by Django 5.2.4 on 2025-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_paymentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار'), (2, 'پرداخت موفق'), (3, 'پرداخت ناموفق')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='user_subscriptiontype',
            field=models.IntegerField(choices=[(1, 'No_Subscription'), (2, 'days_10'), (3, 'days_15'), (4, 'days_30'), (5, 'days_60')], default=1, verbose_name='اشتراک'),
        ),
    ]
