# Generated by Django 5.2.4 on 2025-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentmodel_user_subscriptiontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'پرداخت'},
        ),
    ]
