# Generated by Django 5.2.4 on 2025-08-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymentmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت'},
        ),
    ]
