# Generated by Django 5.2.4 on 2025-08-08 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام اشتراک')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ اشتراک')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('days', models.IntegerField(default=1, verbose_name='روز')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subs_Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptions', verbose_name='اشتراک')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
