# Generated by Django 5.2.4 on 2025-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptions_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subs_buy',
            options={'verbose_name': 'اشتراک'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'زمان'},
        ),
    ]
