# Generated by Django 5.2.4 on 2025-08-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subs_buy_options_alter_subscriptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subs_buy',
            options={'verbose_name': 'اشتراک خریداری شده', 'verbose_name_plural': 'اشتراک خریداری شده'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک'},
        ),
    ]
