# Generated by Django 5.2.4 on 2025-08-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subs_buy_options_alter_subscriptions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='type',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=1, verbose_name='وضعیت'),
        ),
    ]
