# Generated by Django 5.2.4 on 2025-08-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='star',
            new_name='rate',
        ),
    ]
