# Generated by Django 5.2.4 on 2025-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_reviewmodel_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'زمان'},
        ),
    ]
