# Generated by Django 5.2.4 on 2025-08-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'زمان', 'verbose_name_plural': 'زمان'},
        ),
    ]
