# Generated by Django 5.2.4 on 2025-08-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_reviewmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'نظرات', 'verbose_name_plural': 'نظرات'},
        ),
    ]
