# Generated by Django 5.2.4 on 2025-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogcategorymodel_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=1, verbose_name='وضعیت :'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام :'),
        ),
    ]
