# Generated by Django 5.2.4 on 2025-08-04 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogmodel_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='بلاگ'),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='file',
            field=models.ImageField(upload_to='blogs/extra_img/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.blogcategorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='blogs/image.jpg', upload_to='blogs/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'نمایش'), (2, 'عدم نمایش')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'ویژه'), (2, 'عادی')], default=2),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='بلاگ'),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='wishlistmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
