# Generated by Django 5.2.4 on 2025-08-04 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogimagemodel_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='discount_percent',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ'),
        ),
    ]
