# Generated by Django 5.2.4 on 2025-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_discount_percent_blogmodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='blogimagemodel',
            options={'verbose_name': 'عکس پست'},
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'پست'},
        ),
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'verbose_name': 'علاقه مندی ها'},
        ),
    ]
