# Generated by Django 5.2.4 on 2025-08-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'verbose_name_plural': 'علاقه مندی ها'},
        ),
    ]
