# Generated by Django 5.2.4 on 2025-08-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_wishlistmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'دسته بندی ها', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='blogimagemodel',
            options={'verbose_name': 'عکس پست ها', 'verbose_name_plural': 'عکس پست ها'},
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'پست ها', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'verbose_name': 'علاقه مندی ها', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
    ]
