# Generated by Django 5.2.4 on 2025-08-22 08:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'ویژه'), (2, 'عادی')], default=2, verbose_name='نوع'),
        ),
    ]
