# Generated by Django 5.2.4 on 2025-08-31 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogmodel_description_alter_blogmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='discount_percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم'),
        ),
    ]
