# Generated by Django 5.2.4 on 2025-08-31 07:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogmodel_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم'),
        ),
    ]
