# Generated by Django 5.2.4 on 2025-08-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogmodel_description_en_blogmodel_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
